create_config_files( ...
    'experiment_name', 'spikes_opto_on_tree', ...
    'email_for_notifications', 'sh3276@columbia.edu', ...
    'yeti_user', 'sh3276', ...
    'structure_type', 'tree', ...
    'p_lambda_splits', 20, ...
    'p_lambdas_per_split', 1, ...
    'p_lambda_min', 1e+01, ...
    'p_lambda_max', 1e+07);
